[package]
name = "renoa-control"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
axum = { workspace = true, features = ["http1", "json", "ws"] }
futures-util.workspace = true
getrandom.workspace = true
renoa-credential-relay-protocol = { path = "../renoa-credential-relay-protocol", version = "0.1.0" }
renoa-oauth-relay-protocol = { path = "../renoa-oauth-relay-protocol", version = "0.1.0" }
renoa-protocol = { path = "../renoa-protocol", version = "0.1.0" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
url.workspace = true
uuid.workspace = true
webauthn-rs = { workspace = true, features = ["danger-allow-state-serialisation"] }

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
tokio-tungstenite.workspace = true
webauthn-authenticator-rs = { workspace = true, features = ["softpasskey"] }

[lints]
workspace = true
