import { ArrowRight, WarningCircle, Hourglass } from "@phosphor-icons/react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { AgentSection } from "../host-navigation";
import { automations, date, duration, DAY, executions, NOW, totalSeconds, scheduledTimes, statusLabel, time, TODAY } from "./data";
type Props = { enabled: Record<string, boolean>; openRun: (id: string, element: HTMLElement) => void; openAutomation: (id: string) => void; navigate: (section: AgentSection) => void };
export function WorkOverview({ enabled, openRun, openAutomation, navigate }: Props) {
  const today = executions.filter(run => run.started >= TODAY).sort((a, b) => a.started - b.started);
  const attention = today.filter(run => run.status !== "completed").sort((a, b) => b.started - a.started);
  const latest = today.filter(run => run.source === "Direct message").sort((a, b) => b.started - a.started)[0];
  const upcoming = automations.filter(item => enabled[item.id]).flatMap(item => scheduledTimes(item, NOW, NOW + 2 * DAY).map(at => ({ item, at }))).sort((a, b) => a.at - b.at).slice(0, 3);
  const listening = automations.filter(item => enabled[item.id] && item.schedule.kind === "event").length;
  const paused = automations.filter(item => !enabled[item.id]).length;
  return <div className="work-overview">
    <div className="work-heading"><div><h2>At a glance</h2><p>What needs you, what happened, and what starts next.</p></div><span className="work-caption">Today · {date(TODAY)}</span></div>
    <div className="work-day-summary"><div><span className="work-caption">Last message received</span><strong>{latest ? time(latest.started) : "—"}</strong><span className="work-caption">{latest?.title ?? "No messages today"}</span></div><div><span className="work-caption">Today’s work</span><div className="work-outcome-meter" aria-label={`${today.filter(run => run.status === "completed").length} completed, ${today.filter(run => run.status === "waiting").length} awaiting input, ${today.filter(run => run.status === "interrupted").length} interrupted`}>{today.map(run => <Tooltip key={run.id} delayDuration={150}><TooltipTrigger asChild><button data-run-id={run.id} className={cn("work-outcome-segment", run.status)} aria-label={`${run.title} · ${statusLabel[run.status]}`} onClick={event => openRun(run.id, event.currentTarget)} /></TooltipTrigger><TooltipContent sideOffset={8} className="flex max-w-72 flex-col items-start gap-1"><strong>{run.title}</strong><span>{time(run.started)} · {statusLabel[run.status]} · {duration(totalSeconds(run))}</span><span>{run.result}</span></TooltipContent></Tooltip>)}</div><span className="work-caption">{today.filter(run => run.status === "completed").length} completed · {attention.length} need attention</span></div></div>
    <div className="work-overview-columns"><section><div className="run-section-heading"><h3>Needs attention <span className="work-filter-count">{attention.length}</span></h3><Button variant="ghost" size="sm" onClick={() => navigate("activity")}>All activity<ArrowRight data-icon="inline-end" /></Button></div><div className="work-attention-list">{attention.map(run => <button data-run-id={run.id} key={run.id} className="work-attention-row" onClick={event => openRun(run.id, event.currentTarget)}>{run.status === "waiting" ? <Hourglass className="work-attention-wait" size={18} /> : <WarningCircle className="work-failure" size={18} />}<span><strong>{run.title}</strong><span>{run.result}</span><small>{time(run.started)} · {statusLabel[run.status]}</small></span><ArrowRight size={15} /></button>)}</div></section>
      <section><div className="run-section-heading"><h3>Coming up</h3><Button variant="ghost" size="sm" onClick={() => navigate("automations")}>Automations<ArrowRight data-icon="inline-end" /></Button></div><div className="work-upcoming">{upcoming.length ? upcoming.map(({ item, at }) => <button key={`${item.id}-${at}`} onClick={() => openAutomation(item.id)}><time>{time(at)}<small>{at >= TODAY + 2 * DAY ? date(at) : at >= TODAY + DAY ? "Tomorrow" : "Today"}</small></time><i /><span><strong>{item.name}</strong><small>{item.rule}</small></span><ArrowRight size={14} /></button>) : <p className="work-caption">No scheduled work in the next two days.</p>}</div><div className="work-overview-automation-note"><span>{listening} event {listening === 1 ? "listener" : "listeners"} enabled</span><span>{paused} {paused === 1 ? "automation" : "automations"} paused</span></div></section></div>
    <div className="work-overview-configure"><div><h3>How this agent works</h3><p>Model, instructions and capabilities. Connections supply access where a capability needs it.</p></div><Button variant="outline" onClick={() => navigate("configure")}>Configure agent<ArrowRight data-icon="inline-end" /></Button></div>
  </div>;
}
